package P06_NestedTryStatements;

public class NestTry {
    public static void main(String args[]) {
        int a;
        int b;
        int c[] = {1};
        
        try {
            a = args.length;
            
            /* If no command-line args are present,
            the following statement will generate a
            divide-by-zero exception. */
            b = 42 / a;
            
            System.out.println("a = " + a);
            
            try { // Nested try block.
                /* If one command-line is used,
                then a divide-by-zero exception will
                be generated by the following code. */
                if(a == 1) {
                    a = a / (a - a);
                }
                
                /* If two command-line args are used,
                then generate an aout-of-bound exception. */
                if(a == 2) {
                    c[42] = 99;
                }
            } catch(ArrayIndexOutOfBoundsException e) {
                System.out.println("Array index out-of-bounds: " + e);
            }
        } catch(ArithmeticException e) {
            System.out.println("Divide by zero: " + e);
        }
    }
}
